# https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file
name: ml2
channels:
  - defaults
dependencies:
  - numpy=1.19.*
  - pandoc
  - pip
  - python=3.8
  - scipy=1.5.*
  # - tensorflow-gpu
  # - tensorflow
  # - tensorboard
  # - tensorflow-estimator
  - pip:
    - ipywidgets
    - jupyterlab
    - matplotlib==3.3.*
    - pandas==1.1.*
    # - scikit-image=0.16
    - scikit-learn==0.23.*
    - seaborn==0.11.*
