# https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file
# Seperate from regular ML environment, to resolve dependancy issues between tf and numpy
name: dl
channels:
  - defaults
  - conda-forge
dependencies:
  - graphviz
  - numpy=1.20.*
  - pandoc
  - pip
  - python=3.9
  - scipy=1.6.*
  - tensorflow=2.4.*
  - pip:
    - ipywidgets
    - jupyterlab
    - kaggle
    - matplotlib==3.3.*
    - pandas==1.2.*
    - pydot
    - scikit-learn==0.24.*
    - seaborn==0.11.*
