# https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file
name: ml
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy=1.19.*
  - pandoc
  - pip
  - python=3.9
  - python-graphviz
  - scipy=1.5.*
  - pip:
    - ipywidgets
    - folium
    - jupyterlab
    - matplotlib==3.3.*
    - pandas==1.1.*
    - pydotplus
    - scikit-learn==0.23.*
    - seaborn==0.11.*
    - wordcloud
    - xlrd==1.*
